# Generated by Django 5.0.7 on 2024-07-12 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('is_cash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('housing', 'Housing'), ('clothing', 'Clothing'), ('car', 'Car'), ('training', 'Training'), ('salary', 'Salary'), ('sale', 'Sale')], max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.financialaccount')),
            ],
        ),
    ]
